# semantickitti_04 config

# Map information
resolution: 0.1  # 0.3   地图分辨率，第一个数据集0.1，第二个0.3
num_class: 20  # Number of classes 20     对于semantic kitti是35，学长这个20就够

# Sampling resolutions
free_resolution: 100 # Free space sampling resolution 100，这个不知道为啥，这个影响厚实程度，如果用100不采样free点，就会很厚实，就不适合学长录得.   0.5的时候效果就很不错了
ds_resolution: 0.1 # Downsampling factor  0.1 ，不能大于地图分辨率

# Information about range-finder data
scan_num: 200 # How many scans to use  100
max_range: 12 # Sensor max range (m)  -1  最大感知距离，限制一下可以提高建图效率呢，比如学长的需要限制在15

color_num: 4

# Dataset information
query: false
visualize: true
